### ISSUE TITLE
Webhooks: No webhook is called when changing the order of to-dos, adding a due date, etc.

### ISSUE THREAD

**Issue by SeBsZ** [basecamp/bc3-api#106]
Some issues I've seen: 
-No webhook is called when changing the order of to-dos.
-No webhook is called when adding a description/note to a to-do, only when changing an already existing description
-No webhook is called when adding a due date, only when modifying an already existing due date.
-No webhook is called when applauding a comment

There may be more? I hope me finding these issues is useful to you @georgeclaghorn, thanks for your quick help.

**Comment by georgeclaghorn** [comment]
> No webhook is called when changing the order of to-dos.

> No webhook is called when applauding a comment

Intentional. These aren’t among the [documented](https://github.com/basecamp/bc3-api/blob/master/sections/webhooks.md) events that currently trigger webhook deliveries.

> No webhook is called when adding a due date, only when modifying an already existing due date.

[Known](https://github.com/basecamp/bc3-api/issues/77).

> No webhook is called when adding a description/note to a to-do, only when changing an already existing description

This has the same root cause as the previous issue. They’ll be resolved together.

**Comment by archon810** [comment]
Thanks. Is there a plan to resolve #77 soon? It's been open for 3 months.
