### ISSUE TITLE
Trashing TODOs shouldn't hit webhooks for trashing comments

### ISSUE THREAD

**Issue by archon810** [basecamp/bc3-api#108]
Or at least provide a clue that the trashing of comments is happening because a TODO is being trashed, so we can ignore it.

Consider a TODO with 25 comments. Then it gets trashed, and 26 webhooks are hit, spamming our Slack where we only care about 1 message - a TODO has been trashed (along with any comments that got trashed as a result, but that's not useful info).

On the other hand, trashing individual comments is useful info. So we'd like to differentiate between those.

What do you think @georgeclaghorn?

**Comment by georgeclaghorn** [comment]
We’re not likely to make this change. When a to-do is put in the trash, so are its comments.

We might be able to add a flag to the webhook payload that indicates whether the relevant recording inherits its parent’s status. Could you use that to avoid posting to Slack when a comment that inherits its parent’s status is trashed?

**Comment by archon810** [comment]
Absolutely, that'd be a fine solution.

cc @sebsz

**Comment by archon810** [comment]
And by that I mean your latter suggestion.

As I mentioned about the former, "On the other hand, trashing individual comments is useful info. So we'd like to differentiate between those."

**Comment by rosa** [comment]
@archon810 sorry for the delay, we just added the flag mentioned above, `inherits_status`, to the recording object in the webhook payload (and in other payloads including `recording`). You can read about it [here](https://github.com/basecamp/bc3-api/blob/master/sections/webhooks.md#inherited-status).

> "On the other hand, trashing individual comments is useful info. So we'd like to differentiate between those."

This is still true. When you trash/archive a recording, the payload you'll get will indicate `"inherits_status": false` if the recording's trashed/archived status is not inherited from its parent, that is, if the recording was trashed/archived directly. A recording trashed/archived because its parent was trashed will have `"inherits_status": true`.

**Comment by SeBsZ** [comment]
Thanks @rosa, this seems to work. Thanks and I apologize for the late response.
