### ISSUE TITLE
Webhooks: when someone is mentioned, name is not contained in the message

### ISSUE THREAD

**Issue by SeBsZ** [basecamp/bc3-api#112]
For example when a comment is created with the message "@sebs89 take a look at this", the webhook comment_created will contain a "content" that might look like this:

`"content":"\u003cdiv\u003e\u003cbc-attachment sgid=\"BAh7CEkiCGdpZAY6BkVUSSIpZ2lkOi8vYmMzL1BlcnNvbi8xMDI1MjkyNT9leHBpcmVzX2luBjsAVEkiDHB1cnBvc2UGOwBUSSIPYXR0YWNoYWJsZQY7AFRJIg9leHBpcmVzX2F0BjsAVDA=--1edfbfb98c981ede793859159481efe374a8e7bc\" content-type=\"application/vnd.basecamp.mention\"\u003e\u003c/bc-attachment\u003e take a look at this.\u003c/div\u003e"`

Unfortunately this is very difficult to parse. The base64 encoded part does yield a user ID which I can look up using the API, but would it be possible to include a "parsed_content" field or something like it that just includes the "@sebs89" ?

What's the suggested way of handling this?

Thank you

**Comment by archon810** [comment]
@georgeclaghorn Thoughts on this one?

**Comment by rosa** [comment]
@SeBsZ, @archon810, this is the way [mentions are included in rich text content](https://github.com/basecamp/bc3-api/blob/master/sections/rich_text.md#inserting-a-mention). Instead of parsing it, have you tried to use the `url` of the recording included in the payload of the webhook to retrieve it using the corresponding API? You'll get the content expanded as described in the previous link. For example, if you get an event for a comment created, you'll get a payload similar to this in your webhook URL:

```json
{
  "id":123123123,
  "kind":"comment_created",
  ...
  "recording": {
     ...
    "type":"Comment",
    "url":"https://3.basecampapi.com/111111/buckets/22222/comments/123123123.json"
  }
```

You can make a request to the URL in `recording.url` and you'll get an expanded version of the mention, with the name, title and avatar of the person mentioned.

**Comment by SeBsZ** [comment]
Thanks, this works!
