### ISSUE TITLE
Occasionally, assigning a TODO author ends up in a webhook for changed description firing too

### ISSUE THREAD

**Issue by archon810** [basecamp/bc3-api#113]
Every once in a while, an author assigns a TODO to themselves, and I see the corresponding assignment webhook firing, but also right before that a changed description one. Yet the description doesn't change.

I suspect it's due to some encoded character or something else similarly "invisible" as a change to us but looking as a change to your backend comparison function. Maybe an encoded quote or some whitespace symbol.

Most recently, it happened to this TODO: https://3.basecamp.com/3093264/buckets/3005288/todos/457661903 - maybe you can view its history privately. I added it using the Android app, from what I remember, and the author assignment probably happened in the web browser, so maybe there are some fine differences?

**Comment by archon810** [comment]
@georgeclaghorn Any ideas?

**Comment by rosa** [comment]
Hey @archon810, sorry for the massive delay replying. Did you ever figure out what happened with these events? What you described sounds possible, more so if there are different clients involved, but if it's still happening, I can take a look at any requests.

**Comment by archon810** [comment]
Yeah, it's still happening @rosa.

**Comment by rosa** [comment]
@archon810 would you mind [contacting support](https://basecamp.com/support) with more details? Just mention me or this issue, and if you can, include a link to one of the to-dos where that happened recently.

**Comment by archon810** [comment]
If you require a recent case, I'll have to wait till it happens again, and then I'll point it out here.

**Comment by rosa** [comment]
No problem! A recent case would be helpful, yes 😄

**Comment by archon810** [comment]
@rosa it just happened here https://3.basecamp.com/3093264/buckets/3005288/todos/1538242703. Richard assigned it to himself, but a changed description message was generated.

**Comment by archon810** [comment]
![screenshot_20190117-220518](https://user-images.githubusercontent.com/469543/51368450-4cfb3100-1aa4-11e9-9a01-49cd5777d249.png)

**Comment by archon810** [comment]
This explanation makes sense, however "I don't have a good solution for this, unfortunately, this behaviour is intended and expected" is not what I expected to hear.

There must be a workaround, as it's still a bug.

Either your algorithm explicitly ignores this change and doesn't generate a change notification. Or the image isn't modified inline like that by different clients. Or maybe you return a parameter back that signifies the changes were immaterial, so we could ignore the ping. Or some other way.

**Comment by archon810** [comment]
I guess we'll have to disagree on the definition of a bug here, because the behavior is broken, and it's due to the design of the official tools Basecamp developed - app vs web, which decide to mangle the content that isn't touched.

If Basecamp isn't going to fix it, is there a way we can work around it ourselves, such as getting the text of previous and new versions in the ping we get, and comparing the content ourselves, then ignoring when only such changes are detected?

**Comment by rosa** [comment]
> is there a way we can work around it ourselves, such as getting the text of previous and new versions in the ping we get

@archon810, no, sorry 😞 It's not possible to fetch previous versions of a to-do, via the API or the web UI. The only way around this I can think of, if you must edit to-dos from devices with different device pixel ratios, is to not include previewable images attached to the to-do descriptions (they can be added in a comment). Otherwise, the previews will change when editing the to-do, to reflect the new device pixel ratio.

**Comment by archon810** [comment]
I can't control which devices our writers, developers, and editors use, and considering Basecamp offers officially supported solutions on those devices, it's not reasonable to expect that. A user shouldn't have to worry about what aspect ratio their device is.

Outside of implementing a proper solution for this issue's cause (such as doing away with touching the image url itself in the body which tbh I think was a horrible idea from the development standpoint and I'd urge you to phase out), one solution here would be to bring back todo author assignments to be independent from editing all other todo fields. If I tap on the author, just make the author editable, not the whole todo.

**Comment by rosa** [comment]
> A user shouldn't have to worry about what aspect ratio their device is.

Oh, yeah, I totally agree, and wasn't suggesting a user should worry about that, or worry about which devices users access Basecamp with. Sorry if I implied otherwise. 

In general, this behaviour is not a problem at all, it's only a problem with this particular edge case. A very small percentage of users use webhooks, and an even smaller percentage need to track both `todo_assigned` and `todo_description_changed` events.

> one solution here would be to bring back todo author assignments to be independent from editing all other todo fields. If I tap on the author, just make the author editable, not the whole todo

Yep, that would certainly avoid this behaviour. That's a change in the UI that I'm not sure we'll tackle in the future, though. 

Thanks for all your input and patience on this one, @archon810, and sorry that we don't have a better solution for you right now.
