### ISSUE TITLE
Duplicate users returned from /people.json

### ISSUE THREAD

**Issue by crash13override** [basecamp/bc3-api#124]
One of our client is receiving a lots of duplicate users when we call the /people.json endpoint.

All the users returned have a differente basecamp_id and avatar so they are actually different entities, but there are a lot of duplicated emails and names.

This client in particular, just migrated from Basecamp 2 to Basecamp 3. Could this be the source of the problem?

How should I handle this situation? I was hoping to identify the users by their email address, which I thought would be unique, but it's obviously not the case.
How can I make a proper one-to-one link between my app's users and Basecamp's users if I can't rely on the email address? How is this handled in Basecamp when I want to assign a task to someone? How do you know which account to assign if they both have the same email address and name?

Thanks a lot for your help!!!

Luca

**Comment by Rosa** [comment]
@crash13override, it does sound like something went wrong with the migration from Basecamp 2 to 3, so we might need to fix that for your client's account, rather than implementing something in the API that allows you to distinguish between users. Could you send more details about the particular account that is having issues through the form in https://basecamp.com/support? Thanks!

**Comment by crash13override** [comment]
Hi Rosa,

thanks a lot for the reply! after a day or two, the problem magically disappeared. Not sure if the user or you did something, but it worked :)

If I find the issue again I'll notify it through the support channel like you suggest.

Thanks!

**Comment by Rosa** [comment]
Oh, nice! I'm glad it was fixed! Don't hesitate to reach out if something else happens 😄
