### ISSUE TITLE
Add completed and due_on as filters for recordings

### ISSUE THREAD

**Issue by nekromoff** [basecamp/bc3-api#125]
Currently, one is unable to pull just the todos that are incomplete and late. The desired state is not to iterate over countless recordings, but rather be able to filter them by these two parameters.

**Comment by nekromoff** [comment]
Any update? This should be easy to add, right?

**Comment by nekromoff** [comment]
?

**Comment by nekromoff** [comment]
Is this repo even monitored by anyone at Basecamp?

**Comment by GeertClaes** [comment]
@nekromoff Seeing there has been no reply at all I have a feeling nobody from Basecamp monitors this 😞

**Comment by rosa** [comment]
@GeertClaes hey, we do monitor this! We are a really small team and we haven't had the time yet to plan for the kind of improvements like adding this filter is. I'm sorry we didn't reply to the last comment here, we certainly should have replied that one before 😅 

We might add `completed` and `due_on` eventually, but I don't have an estimated time for when that would happen.

**Comment by nekromoff** [comment]
Well, this does not make sense. You are basically forcing everyone to pull *all the existing todos* via your API, therefore putting too much load your servers instead of making small changes to your API code - adding two filters (e.g. by parameters).

Moreover, if I want to keep list of todos updated, I need to pull date e.g. every few hours again and again, iterating over all existing pages of todos.

Instead of getting few todos (or few tens of todos), I have download and go over hundreds (or thousands) of todos.

**Comment by foxontherock** [comment]
@nekromoff I agree that it's too much load to get todos from "archived" or "trashed" projects.  

But, for active projects, you can keep a local cache with very few api call, by fetching these 3 "GET"

/recordings.json?type=Todo&sort=updated_at&direction=desc&status=active
/recordings.json?type=Todo&sort=updated_at&direction=desc&status=archived
/recordings.json?type=Todo&sort=updated_at&direction=desc&status=trashed

That way, when you reach a todo already in your cache, just stop fetching for next page.  You need to do 3 calls, for status=trashed, archived, and active.

But, if one of your cached todo move from an active to archived or inactive bucket or list, you will NOT be notified... because they don't allow us to get todos from inactive projects using the /recordings.json route... That's a non-sense.
So, for these projects, you need to get tons of GET, select * from all lists of all inactive projects... order by not useful order.  That's a FAIL.

**Comment by javan** [comment]
> Moreover, if I want to keep list of todos updated, I need to pull date e.g. every few hours again and again, iterating over all existing pages of todos.

Or, you could use [webhooks](https://github.com/basecamp/bc3-api/blob/master/sections/webhooks.md#webhooks) and get notified when things change.

**Comment by rosa** [comment]
Hey all, sorry for the lack of updates lately! We don't have any plans to add this in the future, so I'm closing this issue. Using webhooks to get notified when to-dos change is the way to go to keep existing to-dos updated on your side. Also:

> because they don't allow us to get todos from inactive projects using the /recordings.json route...

We do plan to add support for that in https://github.com/basecamp/bc3-api/issues/178.
