### ISSUE TITLE
No assignee information on "todo_created" webhook call

### ISSUE THREAD

**Issue by miks** [basecamp/bc3-api#147]
Why it's that?
When changing assignee for already created "to do", I'm getting "todo_assignment_changed" call with "added_person_ids".
There is little use for "todo_created" webhook when no assignee information is included on creation.

**Comment by rosa** [comment]
@miks, the reason for this is that the payload we send for the webhook is related to the event itself, with a generic representation of the [recording](https://github.com/basecamp/bc3-api/blob/master/sections/recordings.md#recordings) involved in the event. For a recording creation event (like `todo_created`), we send the recording that was created, and since that is generic, it doesn't include attributes that only todo have (such as assignees). In the case of a `todo_assignment_changed` event, `added_person_ids` is part of the event details itself. 

In any case, in the `todo_created` response you get the todo's id and the todo's bucket's id, and you can use them to get the assignees in a subsequent call to `GET /buckets/:bucket_id/todos/:id.json`.
