### ISSUE TITLE
Invalid Notes content on "todo_created", "todo_description_changed" webhooks call

### ISSUE THREAD

**Issue by lokeshpahal** [basecamp/bc3-api#153]
I am not getting the **Notes** content in both `todo_description_changed` and `todo_created` webhooks call.
Instead of the **Notes** content I am getting ToDo title.

**here you can see:**

u 'title': u 'Login Screen V1.1',
u 'bucket': {
    u 'type': u 'Project',
    u 'id': XXXXXXX,
    u 'name': u 'Devops'
},
u 'updated_at': u '2017-12-15T13:41:23.015+05:30',
u 'content': u 'Login Screen V1.1',

why is this?

**Comment by rosa** [comment]
Hey @lokeshpahal! A todo's content is the same as its title. You can see that in [the sample response](https://github.com/basecamp/bc3-api/blob/master/sections/todos.md#example-json-response-1) from the `GET /buckets/:bucket_id/todos/:id.json` endpoint. The notes are included as `description` there. Since in the webhook response you get the todo's `id` and the todo's bucket's `id`, you can use them to get the notes in a subsequent call to `GET /buckets/:bucket_id/todos/:id.json`. Does this help?

**Comment by ArondeParon** [comment]
I just came across this issue as well, but perhaps the documentation on this could be clarified?

If I see a "todo_description_changed" event firing, as a user, I expect the description to be present. The current response is a bit confusing and I bet a lot of developers could be saved a lot of trouble if this were either amended or documented 🙂

**Comment by rosa** [comment]
@ArondeParon good point. We mention in the webhooks documentation that the format of the recording is the basic one with only common fields plus `title` and `content`, but I have added a [small clarifying example to that part](https://github.com/basecamp/bc3-api/commit/7cbb075f7b1eae712cc5565cc643ad02b59a5722). You are right that the todo's case is particularly confusing because of having `title`, `content` (that are the same thing) and `description`.
