### ISSUE TITLE
Updating Todo assignees (missing documentation)

### ISSUE THREAD

**Issue by akf** [basecamp/bc3-api#174]
I've been trying to get my app to update BC3 Todos via the API. I hit a snag with assignees, which I only got around by guessing (although a thorough search of the issues here might have helped me). 

To wit, on a PUT to the /buckets/n/todos/m.json endpoint, the assignees field of the object is not used. Instead, including just the assignee's ids in an "assignee_ids" array is what's required. 

Also, I noticed that some of my updates un-assigned basecamp todos, and I'm pretty sure it's because I had omitted the assignee_ids field altogether -- easy to do, since it's not included in the payload from Basecamp when you GET a Todo. I worry that this might also be the case for person fields like "completion_subscribers," but haven't investigated that. (I would never update this from my side.) 

(It would also be a reassuring feature to be able to execute a PATCH instead, passing only the fields to be updated.)

**Comment by rosa** [comment]
@akf sorry for the trouble with these endpoints. I'll try to improve the documentation around updating todos, making it more explicit. [Right now](https://github.com/basecamp/bc3-api/blob/master/sections/todos.md#update-a-to-do) we say:

> **Required parameters**: Pass all existing parameters in addition to those being updated. For example, to update the to-do's content from Create a to-do

And [the example itself](https://github.com/basecamp/bc3-api/blob/master/sections/todos.md#example-json-request-1):

```json
{
  "content": "Only changing content! Passing the rest to preserve them.",
  "description": "<div><em>Try that new language!</em></div>",
  "due_on": "2016-05-01"
}
```

So we are already explicit about having to include other parameters to preserve them, which includes `assignee_ids`. 

I agree it's not clear you have to use the same parameters as the `POST /buckets/1/todolists/3/todos.json` endpoint, rather than those returned by `GET /buckets/1/todos/2.json`. I'll improve this.

**Comment by akf** [comment]
Right, it's the latter that wasn't clear. I had missed the assignee_ids and completion_subscriber_ids in the POST endpoint -- the first, I think I just forgot when I started trying to do an update; the completion_subscriber_ids we don't interact with at all on our end. Since our app only maps an "action item" to a subset of the Basecamp To-do, I retrieve the To-do and then update selected fields before POSTing it back. 

I definitely read "pass all existing parameters" as meaning all the parameters that come back in a GET request.

**Comment by rosa** [comment]
Yeah, that's totally understandable. I listed all parameters explicitly now, I hope that makes it clearer!
