### ISSUE TITLE
API ToDo - make PROJECT optional

### ISSUE THREAD

**Issue by petrsidlo** [basecamp/bc3-api#176]
Current implementation of API is unfortunatelly hard to use, as it requires to specify which project is my to-do from. And to create new ZAP for each new to-do list. Not quite elegant solution. And PROJECTS are created quite often ...which makes the current API unrealiable.

Why it is important? Because I keep my all tasks in Trello (regardles where it is coming from - we are using also other apps with to-dos, like Pipedrive, Trello etc). Its impossible to manage my days without having all my commitments in one place, instead of several apps and this would help great deal. I also believe it might actually be simpler to implement than for me to write this email (SELECT * FROM TASKS WHERE OWNER = ? :-))). Ok may be not ... but please consider :-) In my ideal world - any task being assigned to me anywhere in Basecamp is being transfered to Trello through one single ZAP … and I can sleep well :-)

Thank you!

**Comment by rosa** [comment]
@petrsidlo have you tried to use the Recording endpoints? Specifically [Get recordings](https://github.com/basecamp/bc3-api/blob/master/sections/recordings.md#get-recordings). The project (`bucket`) is optional, and you can specify only `type=Todo` to get only to-dos. 

It doesn't include anything to filter based on the assignee, but since your question is specifically about making project optional, I think this might help!

**Comment by petrsidlo** [comment]
hello, thank you very much for your reply, but I am not probably able reply, as I am not a programmer - just using the API only through Zapier ...

![image](https://user-images.githubusercontent.com/38252009/38577970-ca795376-3d02-11e8-8005-0c3b47e57030.png)

**Comment by rosa** [comment]
@petrsidlo ah! Got it, I misunderstood your question. I had a look at the Zapier's BC3 - Trello workflow for creating Trello cards when a new to-do is created in Basecamp and I believe this is implemented using [our webhooks](https://github.com/basecamp/bc3-api/blob/master/sections/webhooks.md#webhooks). Unfortunately, the project can't be made optional there, since webhooks as of now are always associated to a specific project. 

We might reconsider this in the future, for example, to also allow something like #121, but it's not in the backlog right now. Sorry about that!
