### ISSUE TITLE
Retreaving recordings for archived projects

### ISSUE THREAD

**Issue by gjokov** [basecamp/bc3-api#178]
I’m trying to retrieve all recordings for all projects. 
Method /projects/recordings.json retrieves the recordings for active projects, but not for Archived projects. I specifically tested this for Todolists.
Even if i specify the Id of the archived project in the bucket parameter, I’m getting error: Not found.
Please help

**Comment by rosa** [comment]
@gjokov, have you tried with the specific endpoints for each kind of recording? For example, for to-do lists: [Get to-do lists](https://github.com/basecamp/bc3-api/blob/master/sections/todolists.md#get-to-do-lists). This should work for archived projects too.

**Comment by gjokov** [comment]
@rosa   Yes, but i have 500 archived projects. With /projects/recordings.json i would retrieve all todolists (or todos) with one request. If i go with the specific endpoint, i will need to have one request per projects, plus additional requests to retrieve the todosets. That makes at least 500 request per each kind of recording. 
Please, is there a way to retrieve all the recordings for all archived projects?
Thanks

**Comment by Sunhat** [comment]
Hi @gjokov , probably a bit too late.

The basecamp api is pretty poorly structured and inconsistent. They focused on Headers and Caching, and failed to deliver data in the fewest number of requests possible.

if you send recordings.json?status=archived, recordings.json?status=trashed, recordings.json?status=active

you'll get the records you need.

**Comment by rosa** [comment]
As mentioned [in this other comment](https://github.com/basecamp/bc3-api/issues/184#issuecomment-398449255), the `status` parameter in `GET /recordings.js` endpoint refers to the recordings' status, not the bucket's. Unfortunately that endpoint doesn't support archived projects yet, that's why I suggested using the specific endpoints for each type. I can see how this is not convenient at all for 500 archived projects, @gjokov. 

We might add support for archived buckets to the `GET /recordings.js` endpoint in the future, though!

**Comment by foxontherock** [comment]
It can be very nice to get these todos from the /recordings.json endpoint, because we are caching data locally, and it's easy from that link to get data ordered by last_update DESC.  That way, I only get the first page and my cache is up-to-date quickly with 3 quick calls (status active + archived + deleted).  99% of the time, I don't need to get to page 2 using that method.

**Comment by foxontherock** [comment]
That's good news @rosa , do you have any idea when that feature will be available ? (getting recording from archived projects)?  May I suggest you to begin by allowing us to get them when using the "bucket" parameter if you don't want to change the default behavior of the endpoint... we will be able to provide a list of comma-separated bucket ids (deleted and archived), and get results, instead of a 404.

**Comment by rosa** [comment]
This should be fixed now! Now ids for archived projects provided in the `bucket` parameter won't raise a 404, they'll work just fine (if they are visible to the current user, of course). You can combine bucket ids for any bucket status there. The default behaviour if `bucket` is not provided will continue to be using all active buckets visible to the current user.
