### ISSUE TITLE
“My Schedules” seems to be missing (or broken!)

### ISSUE THREAD

**Issue by ticky** [basecamp/bc3-api#185]
Hi there,

I’m trying to make something which interfaces with schedule entries, but running up against the problem that there’s no currently supported way to look up a user’s personal schedule individually.

From poking the API directly, it looks like `my/schedules.json` _exists_, but returns a 500. It’d be great if this could be fixed/added/documented, as it’s exactly what I need to get this working!

Otherwise, I’m going to have to do this manually, fetching the schedules from every project a user has access to, which seems suboptimal both from my side, and from your side as far as load is concerned.

**Comment by rosa** [comment]
Hey @ticky! Unfortunately `/my/schedules.json` is not part of the API, that's why it's not documented. We only support fetching schedules and [schedule entries](https://github.com/basecamp/bc3-api/blob/master/sections/schedule_entries.md#schedule-entries) for each project, as you noticed. 

We might add `/my/schedules` in the future, but I don't have an estimation of when that might happen.

**Comment by rosa** [comment]
Hi again @ticky! We are trying to keep [realistic expectations](https://github.com/basecamp/api#realistic-expectations) about our API, and we don't have any plans to add support for a `/my/schedule.json` endpoint in the future, so I'm closing this issue. Fetching schedules and schedule entries for each project is the way to go.
