### ISSUE TITLE
trashing a comment 

### ISSUE THREAD

**Issue by fearless-stu** [basecamp/bc3-api#208]
In the [API docs it has a link](https://github.com/basecamp/bc3-api/blob/master/sections/comments.md#comments) for "Trashing a comment" but it goes to "trashing a recording". From this and other discussions I've seen it indicates it's not possible to trash a single comment from the API. Is that right - even though you can in the webUI?

I've tried what I think ought to be the API 
`PUT https://3.basecampapi.com/<product>/buckets/<project>/comments/<comment>/status/trashed.json `,  but I get a 404 not found
Is there an undocumented API or can we get it added please?

Stuart

**Comment by rosa** [comment]
Hey @fearless-stu! The docs are right, comments are recordings, and all recordings are trashed in the same way. Your URL is not correct, [following the docs to trash recordings](https://github.com/basecamp/bc3-api/blob/master/sections/recordings.md#trash-a-recording), the URL should look as 
```
https://3.basecampapi.com/<account_id>/buckets/<bucket_id>/recordings/<recording_id>/status/trashed.json
```

`recording_id` is the ID of the comment. Notice `recordings` in the path, instead of `comments`.

**Comment by fearless-stu** [comment]
Thanks Rosa. I hadn't quite understood that from the docs. Now it works for me perfectly. 
Thankyou very much!

Stuart
