### ISSUE TITLE
How I can send a ping?

### ISSUE THREAD

**Issue by joaothallis** [basecamp/bc3-api#217]

**Comment by rosa** [comment]
Hey @joaothallis, you can't. The closest you could do would be using [chatbots](https://github.com/basecamp/bc3-api/blob/master/sections/chatbots.md#chatbots). You can ping an interactive chatbot using the UI and then have the chatbot reply directly to the ping.

**Comment by joaothallis** [comment]
Thanks @rosa!

**Comment by jeissonneira** [comment]
@rosa We found a way to send a ping via a chatbot but not necessarily as a reply. Works well but wanted to make sure we are not doing something not intended by the API. I also emailed @dhh about it.

**Comment by rosa** [comment]
@jeissonneira, would you mind emailing rosa@basecamp.com about it?

**Comment by jeissonneira** [comment]
Sent. Thank you @rosa!

**Comment by rosa** [comment]
For the record, thanks to @jeissonneira use case, I realised I wasn't completely clear when I said the way to achieve this would be to initiate a ping with the chatbot via the UI and then have the chatbot reply to it. It sounds as if the chatbot could only ping the user in the _immediate_ reply to the user's message. This is not the case! The only requirement is that the user _initiates_ the ping so that the ping exists. Once the ping exists, the chatbot can continue posting to this ping as if it was a Campfire. The only thing the chatbot can't do is to start a new ping with a user that hasn't pinged them before.

**Comment by htkz** [comment]
Hi guys, I am still trying to use the chatbot to reply to the ping. Would you mind sharing the API to reply to ping using the chatbot?
I have tried ```POST /integrations/$CHATBOT_KEY/circles/$CIRCLE_ID/lines.json```, but it doesn't work.
I really can not guess the API for the chatbot to reply to the ping.

**Comment by rosa** [comment]
Hey @htkz, you can't guess the API and don't need to! You should get the URL to post replies from the payload sent to your configured URL. When the chatbot is invoked, the payload described [here](https://github.com/basecamp/bc3-api/blob/master/sections/chatbots.md#chatbots) includes a callback URL, under `callback_url`. This is the URL you should use to post your response from the bot.

I hope this helps!

**Comment by htkz** [comment]
Thanks for your answer, it works now. @rosa
