### ISSUE TITLE
Chat bot to ping everyone in the organization

### ISSUE THREAD

**Issue by yashin5** [basecamp/bc3-api#256]
Hi guys, whats up?

The api have the feature to make pings?

**Comment by rosa** [comment]
Hi @yashin5! Not really. You can't have a chatbot ping someone in the account if the bot is the one who needs to initiate the ping. The closest is to have someone in your account ping the chatbot with a command, and the chatbot would respond in the same ping. Another possibility is to have the chatbot [create a Campfire line](https://github.com/basecamp/bc3-api/blob/master/sections/chatbots.md#create-a-line) with a mention for someone in your org instead of pinging them (for notification purposes this will have the same effect as a ping).

**Comment by jeissonneira** [comment]
@yashin5 What exactly are you trying to do? We may have a solution for you.
