### ISSUE TITLE
Question about rate limiting

### ISSUE THREAD

**Issue by rvanbaalen** [basecamp/bc3-api#336]
Hi there,

Not really an issue, more of a question about rate limiting.

I noticed the following: 
https://github.com/basecamp/bc3-api#rate-limiting-429-too-many-requests

> You can perform up to 50 requests per 10-second period from the same IP address. If you exceed this limit, you'll get a [429 Too Many Requests](http://tools.ietf.org/html/draft-nottingham-http-new-status-02#section-4) response for subsequent requests. Check the Retry-After header to see how many seconds to wait before retrying the request.

How does this work for integrations / 3rd party applications?

For instance. If my Basecamp integration has 1000 (or 10k, 100k) users who all connected their Basecamp account, I could quickly run out of the 50 requests per 10 seconds.

Isn't the rate limit supposed to be per (connected) user/access token?

**Comment by jeremy** [comment]
Hey @rvanbaalen, thanks for asking. Rate limiting primarily protects our infrastructure from "hot" usage patterns - commonly caused by things like infinite-loop or retry bugs rather than operating at huge scale. In these cases, limiting by access token affords little protection, whereas limiting by IP does.

Also of note:
* Rate-limiting applies to all requests, not only those authorized by an access token.
* We run multiple rate limiters with a variety of different criteria, limits, and time windows.
* We may introduce and remove limits dynamically based on changes in API traffic distribution.

The 50req/10sec/IP limit is long-lived and generally stricter than other limits, so it's the one to describe in API docs. 😊

The takeaway, however, is to implement as if rate limits are unknown by checking for 429 responses and adhering to their Retry-After guidance so your apps are resilient against any limiting behavior.

Re. scaling up to thousands of users - please do get in touch if you hit scaling limitations with these limits. We've found they're quite adequate even for very large scale integrators, but we're eager to see those limits tested. 🪄
