### ISSUE TITLE
Features: Following To-Do

### ISSUE THREAD

**Issue by nilesuan** [basecamp/bc3-api#59]
Requesting docs for adding to-do followers if it is exposed.

**Comment by rosa** [comment]
We don't have a specific endpoint to add subscribers, but we do provide a way to add assignees and notify them about the assignments, and since recently, we also provide a way to subscribe people to be notified on todo completion. Check `completion_subscriber_ids` in the [todo creation endpoint](https://github.com/basecamp/bc3-api/blob/master/sections/todos.md#create-a-to-do).

**Comment by rosa** [comment]
@nilesuan sorry, I lied in my previous comment. You can add subscribers using the specific `subscription_url` associated to each recording (see example [here](https://github.com/basecamp/bc3-api/blob/master/sections/todos.md#get-to-dos)). I'll document this!

**Comment by rosa** [comment]
Done! You can find how to follow/unfollow a todo or any other kind of subscribable recording [here](https://github.com/basecamp/bc3-api/blob/master/sections/subscriptions.md#subscriptions).
