### ISSUE TITLE
Github Chatbot fails with a 400 error code

### ISSUE THREAD

**Issue by toddgeist** [basecamp/bc3-api#63]
I very carefully followed the instructions. But I am getting a 400 error with every message.

```{"error":"No chat message content found in the request body"}```

The Github repo is an org repo. Not sure that matters.

If there is a better place to post this error please let me know

**Comment by javan** [comment]
That's to be expected currently because we only process *some* events (most push, issue, and status events) from GitHub's webhook payloads. Apologies for the lack of documentation and for the confusing 400s. We'll improve things.

Here's an example from one of our repos:
<img width="790" alt="screen shot 2016-09-29 at 11 32 07 am" src="https://cloud.githubusercontent.com/assets/5355/18960627/633ea080-8638-11e6-8531-3371321ce6fb.png">

---

<img width="272" alt="screen shot 2016-09-29 at 11 34 27 am" src="https://cloud.githubusercontent.com/assets/5355/18960693/a1d3a804-8638-11e6-929d-604acfeacc1b.png">

**Comment by toddgeist** [comment]
Ok.  I got it to work with a New Issue.  

It would be nice if Issue Comments were also sent. That's what I was looking for.

Thanks

Todd

**Comment by javan** [comment]
Yeah, hopefully we can expand to handle all events and let you pick and choose the ones you want when configuring the webhook on GitHub,

**Comment by toddgeist** [comment]
sounds like a plan :-)
