### ISSUE TITLE
Question: Will Basecamp 2 API be phased out ? 

### ISSUE THREAD

**Issue by viraf** [basecamp/bc3-api#66]
Our current app integration is using Basecamp 2 API (BCX). We are currently working on a Basecamp 3 based integration. Is Basecamp 2 phased out for all Basecamp customers or do they still have the option to continue using Basecamp 2 ? 

The reason for my question is to determine if we have to continue supporting Basecamp 2 users along with Basecamp 3 or just the latest.

Thank you.

**Comment by eileencodes** [comment]
Hi @viraf! Since Basecamp 2 and Basecamp are completely separate applications we plan to support both until [the end of the internet](https://basecamp.com/about/policies/until-the-end-of-the-internet). 

You don't have to worry about us phasing out the Basecamp 2 API or application. If you find any issues with the [Basecamp 2 API](https://github.com/basecamp/bcx-api) please be sure to report them on that repository!
