### ISSUE TITLE
Example in Javascript/Jquery

### ISSUE THREAD

**Issue by RobertJGabriel** [basecamp/bc3-api#70]
Hey,

im trying to do a request for basecamp 3 api.

But keep getting a 405 error.

When I do a curl it works fine. Was wondering  could someone throw up a javascript/jquery example for https://launchpad.37signals.com/authorization.json

Thank you so much, been stuck for while.

**Comment by rosa** [comment]
Hey @RobertJGabriel! Sorry for the super late reply 😓A 405 error suggests you might be trying to hit `/auhtorization.json` with something else than a `GET`, but since you mention jquery, you might be just running into #99 🤔 Since using the API from JavaScript in the browser is not going to work just yet, I'll close this in favour of #54.
